SELECT S.*, P.Z AS PHOTOZ,P.ZERR AS PHOTOZ_ERR,
  Q.DERED_U,Q.DERED_G,Q.DERED_R,Q.DERED_I,Q.DERED_Z,
  
  Q.MODELMAGERR_U,Q.MODELMAGERR_G,Q.MODELMAGERR_R,Q.MODELMAGERR_I,Q.MODELMAGERR_Z,
  
  Q.TYPE AS PHOTPTYPE,
  
  Q.PETRORAD_U,Q.PETRORAD_G,Q.PETRORAD_R,Q.PETRORAD_I,Q.PETRORAD_Z,
  Q.PETRORADERR_U,Q.PETRORADERR_G,Q.PETRORADERR_R,Q.PETRORADERR_I,Q.PETRORADERR_Z,
  
  Q.DEVRAD_U,Q.DEVRADERR_U,Q.DEVRAD_G,Q.DEVRADERR_G,Q.DEVRAD_R,Q.DEVRADERR_R,
  Q.DEVRAD_I,Q.DEVRADERR_I,Q.DEVRAD_Z,Q.DEVRADERR_Z,
  Q.DEVAB_U,Q.DEVAB_G,Q.DEVAB_R,Q.DEVAB_I,Q.DEVAB_Z,
  
  Q.EXTINCTION_U,Q.EXTINCTION_G,Q.EXTINCTION_R,
  Q.EXTINCTION_I,Q.EXTINCTION_Z,
  
  Q.CMODELMAG_U,Q.CMODELMAGERR_U,
  Q.CMODELMAG_G,Q.CMODELMAGERR_G,
  Q.CMODELMAG_R,Q.CMODELMAGERR_R,
  Q.CMODELMAG_I,Q.CMODELMAGERR_I,
  Q.CMODELMAG_Z,Q.CMODELMAGERR_Z,
  

  Q.PSFMAG_U - Q.EXTINCTION_U as PSFMAG_U, Q.PSFMAGERR_U, 
  Q.PSFMAG_G - Q.EXTINCTION_G as PSFMAG_G, Q.PSFMAGERR_G, 
  Q.PSFMAG_R - Q.EXTINCTION_R as PSFMAG_R, Q.PSFMAGERR_R, 
  Q.PSFMAG_I - Q.EXTINCTION_I as PSFMAG_I, Q.PSFMAGERR_I, 
  Q.PSFMAG_Z - Q.EXTINCTION_Z as PSFMAG_Z, Q.PSFMAGERR_Z, 
  
  Q.FIBERMAG_U - Q.EXTINCTION_U as FIBERMAG_U ,Q.FIBERMAGERR_U,
  Q.FIBERMAG_G - Q.EXTINCTION_G as FIBERMAG_G ,Q.FIBERMAGERR_G,
  Q.FIBERMAG_R - Q.EXTINCTION_R as FIBERMAG_R ,Q.FIBERMAGERR_R,
  Q.FIBERMAG_I - Q.EXTINCTION_I as FIBERMAG_I ,Q.FIBERMAGERR_I,
  Q.FIBERMAG_Z - Q.EXTINCTION_Z as FIBERMAG_Z ,Q.FIBERMAGERR_Z,
  Q.EXPAB_U,Q.EXPRAD_U,Q.EXPPHI_U,
  Q.EXPAB_G,Q.EXPRAD_G,Q.EXPPHI_G,
  Q.EXPAB_R,Q.EXPRAD_R,Q.EXPPHI_R,
  Q.EXPAB_I,Q.EXPRAD_I,Q.EXPPHI_I,
  Q.EXPAB_Z,Q.EXPRAD_Z,Q.EXPPHI_Z,
  
  Q.FRACDEV_U,Q.FRACDEV_G,Q.FRACDEV_R,Q.FRACDEV_I,Q.FRACDEV_Z,
  
  Q.Q_U,Q.U_U,Q.Q_G,Q.U_G,Q.Q_R,Q.U_R,
  Q.Q_I,Q.U_I,Q.Q_Z,Q.U_Z,
  
  Q.EXPMAG_R - Q.EXTINCTION_R as EXPMAG_R, Q.EXPMAGERR_R
  
INTO MYDB.SHREDDED1_SDSS_DR12_PHOT
  
FROM MYDB.SHREDDED1_SDSS_DR12 AS S 
   
JOIN PHOTOOBJALL AS Q ON S.OBJID=Q.OBJID  
  
LEFT OUTER JOIN PHOTOZ AS P ON S.OBJID=P.OBJID